#!/usr/bin/env python3
from __future__ import annotations

import json
import os
from pathlib import Path


def rust_string_literal(value: str) -> str:
    out = ['"']
    for ch in value:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= code <= 0x7E:
            out.append(ch)
        else:
            out.append(f"\\u{{{code:X}}}")
    out.append('"')
    return "".join(out)


def rust_byte_string_literal(value: str) -> str:
    b = value.encode("ascii")
    out = ['b"']
    for byte in b:
        if byte == 0x5C:  # backslash
            out.append("\\\\")
        elif byte == 0x22:  # quote
            out.append('\\"')
        elif 0x20 <= byte <= 0x7E:
            out.append(chr(byte))
        else:
            out.append(f"\\x{byte:02X}")
    out.append('"')
    return "".join(out)


def find_html_crate_root(start: Path) -> Path:
    cur = start
    while True:
        if (cur / "data" / "entities.json").is_file() and (cur / "src").is_dir():
            return cur
        if cur.parent == cur:
            raise RuntimeError("Could not find crates/html root (expected data/entities.json)")
        cur = cur.parent


def main() -> None:
    root = find_html_crate_root(Path(__file__).resolve())
    data_path = root / "data" / "entities.json"

    output_default = root / "src" / "entities_html5.rs"
    output_path = Path(os.environ.get("HTML5_ENTITIES_OUTPUT", str(output_default)))

    entities = json.loads(data_path.read_text(encoding="utf-8"))
    table: list[tuple[bytes, str, str]] = []
    max_len = 0

    for name, payload in entities.items():
        if not name.endswith(";"):
            continue
        chars = payload["characters"]
        name_bytes = name.encode("ascii")
        max_len = max(max_len, len(name_bytes))
        table.append((name_bytes, name, chars))

    table.sort(key=lambda item: item[0])

    lines = [
        "// @generated by crates/html/tools/generate_entities_html5.py",
        "// DO NOT EDIT BY HAND.",
        "",
        "pub(crate) struct Html5Entity {",
        "    pub name: &'static [u8],",
        "    pub value: &'static str,",
        "}",
        "",
        f"pub(crate) const MAX_HTML5_ENTITY_LEN: usize = {max_len};",
        "",
        "#[rustfmt::skip]",
        "pub(crate) static HTML5_ENTITIES: &[Html5Entity] = &[",
    ]

    for _, name, chars in table:
        name_literal = rust_byte_string_literal(name)
        value_literal = rust_string_literal(chars)
        lines.append(f"    Html5Entity {{ name: {name_literal}, value: {value_literal} }},")

    lines.append("];")
    lines.append("")
    output_path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
