use crate::replaced::intrinsic::IntrinsicSize;
use crate::{
    BoxKind, ListMarker, ReplacedElementInfoProvider, ReplacedKind, box_kind_debug_label,
    classify_replaced_kind, intrinsic_size_debug_label, list_marker_debug_label, node_debug_label,
    replaced_kind_debug_label,
};
use css::{ComputedStyle, Display, StyledNode};
use html::{Node, internal::Id};
use std::fmt::{self, Write};

/// Stable index for a generated layout box in a frame-local box tree.
///
/// Box IDs are deterministic for a fixed style tree and generation environment:
/// nodes are assigned in preorder as they are generated.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BoxId(usize);

impl BoxId {
    pub fn index(self) -> usize {
        self.0
    }
}

/// Stable frame-local identity of the box that provides a containing block.
///
/// W5 models containing blocks as relationships between generated boxes. The
/// ID wraps the establishing `BoxId` so future layout modes can distinguish
/// "this box" from "the containing block this box resolves against" without
/// relying on raw parent traversal.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ContainingBlockId(BoxId);

impl ContainingBlockId {
    pub fn box_id(self) -> BoxId {
        self.0
    }

    pub fn index(self) -> usize {
        self.0.index()
    }
}

/// Stable frame-local identity of a formatting context root.
///
/// W6 models the supported normal-flow block formatting scope as generated-box
/// identity. This is intentionally separate from DOM parentage and from
/// containing-block identity so later layout modes can refine context roots
/// without changing the source tree contract.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct FormattingContextId(BoxId);

impl FormattingContextId {
    pub fn box_id(self) -> BoxId {
        self.0
    }

    pub fn index(self) -> usize {
        self.0.index()
    }
}

/// Formatting-context kinds modeled by the current layout subset.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FormattingContextKind {
    /// Borrowser's W6 normal-flow block formatting scope.
    Block,
}

/// How a generated box participates in the current block-flow model.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BlockFormattingParticipation {
    /// The document/root generated box that seeds the initial block context.
    Root,
    /// A block-level normal-flow participant in an ancestor block context.
    BlockLevel,
    /// Inline-level content participating inside a block container's inline flow.
    InlineLevel,
    /// Atomic inline-level participant whose descendants use its own block scope.
    AtomicInline,
    /// Reserved for generated boxes that are not current block-flow participants.
    None,
}

/// High-level reason a box exists in the generated box tree.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BoxGenerationRole {
    DocumentRoot,
    DocumentElement,
    OrdinaryElement,
    TextRun,
    Anonymous(AnonymousBoxKind),
    Marker,
}

/// Anonymous-box categories generated by layout-owned box-generation rules.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AnonymousBoxKind {
    Block,
    Inline,
}

/// Decision produced by display-to-box generation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DisplayBoxGeneration {
    SuppressSubtree(BoxSuppressionReason),
    GeneratePrincipalBox(PrincipalBox),
}

/// Reason a styled node does not generate a layout box.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BoxSuppressionReason {
    CommentNode,
    DisplayNone,
}

/// Metadata for the principal box generated by one styled source.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PrincipalBox {
    role: BoxGenerationRole,
    kind: BoxKind,
    behavior: DisplayBoxBehavior,
}

impl PrincipalBox {
    pub fn role(self) -> BoxGenerationRole {
        self.role
    }

    pub fn kind(self) -> BoxKind {
        self.kind
    }

    pub fn behavior(self) -> DisplayBoxBehavior {
        self.behavior
    }
}

/// Supported display-driven layout participation behavior.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DisplayBoxBehavior {
    DocumentRoot,
    DocumentElement,
    Block,
    Inline,
    InlineBlock,
    ListItem,
    TextRun,
    ReplacedInline,
    Anonymous,
    Marker,
}

/// Source relationship for a generated layout box.
///
/// Boxes may be directly DOM-backed or generated by layout-owned box-generation
/// rules. Anonymous boxes are generated for the supported block/inline mixing
/// subset. Marker boxes are reserved for future independent marker generation.
#[derive(Clone, Copy)]
pub enum BoxSource<'style_tree, 'dom> {
    DomNode(&'style_tree StyledNode<'dom>),
    Anonymous {
        parent: &'style_tree StyledNode<'dom>,
        kind: AnonymousBoxKind,
    },
    Marker {
        list_item: &'style_tree StyledNode<'dom>,
    },
}

impl fmt::Debug for BoxSource<'_, '_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
            BoxSource::DomNode(node) => f
                .debug_struct("DomNode")
                .field("node_id", &node.node_id)
                .finish(),
            BoxSource::Anonymous { parent, kind } => f
                .debug_struct("Anonymous")
                .field("parent_node_id", &parent.node_id)
                .field("kind", &kind)
                .finish(),
            BoxSource::Marker { list_item } => f
                .debug_struct("Marker")
                .field("list_item_node_id", &list_item.node_id)
                .finish(),
        }
    }
}

impl<'style_tree, 'dom> BoxSource<'style_tree, 'dom> {
    pub fn direct_styled_node(self) -> Option<&'style_tree StyledNode<'dom>> {
        match self {
            BoxSource::DomNode(node) => Some(node),
            BoxSource::Anonymous { .. } | BoxSource::Marker { .. } => None,
        }
    }

    pub fn anchor_styled_node(self) -> &'style_tree StyledNode<'dom> {
        match self {
            BoxSource::DomNode(node) => node,
            BoxSource::Anonymous { parent, .. } => parent,
            BoxSource::Marker { list_item } => list_item,
        }
    }

    pub fn direct_node_id(self) -> Option<Id> {
        self.direct_styled_node().map(|node| node.node_id)
    }

    pub fn anchor_node_id(self) -> Id {
        self.anchor_styled_node().node_id
    }
}

/// A generated layout box node before final geometry is computed.
pub struct BoxNode<'style_tree, 'dom> {
    id: BoxId,
    parent: Option<BoxId>,
    children: Vec<BoxId>,
    role: BoxGenerationRole,
    kind: BoxKind,
    source: BoxSource<'style_tree, 'dom>,
    style: &'style_tree ComputedStyle,
    display: Display,
    display_behavior: DisplayBoxBehavior,
    containing_block: Option<ContainingBlockId>,
    establishes_containing_block: bool,
    formatting_context: Option<FormattingContextId>,
    establishes_formatting_context: Option<FormattingContextKind>,
    block_formatting_participation: BlockFormattingParticipation,
    list_marker: Option<ListMarker>,
    replaced: Option<ReplacedKind>,
    replaced_intrinsic: Option<IntrinsicSize>,
}

impl fmt::Debug for BoxNode<'_, '_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("BoxNode")
            .field("id", &self.id)
            .field("parent", &self.parent)
            .field("children", &self.children)
            .field("role", &self.role)
            .field("kind", &self.kind)
            .field("source", &self.source)
            .field("display", &self.display)
            .field("display_behavior", &self.display_behavior)
            .field("containing_block", &self.containing_block)
            .field(
                "establishes_containing_block",
                &self.establishes_containing_block,
            )
            .field("formatting_context", &self.formatting_context)
            .field(
                "establishes_formatting_context",
                &self.establishes_formatting_context,
            )
            .field(
                "block_formatting_participation",
                &self.block_formatting_participation,
            )
            .field("list_marker", &self.list_marker)
            .field("replaced", &self.replaced)
            .field("replaced_intrinsic", &self.replaced_intrinsic)
            .finish()
    }
}

impl<'style_tree, 'dom> BoxNode<'style_tree, 'dom> {
    pub fn id(&self) -> BoxId {
        self.id
    }

    pub fn parent(&self) -> Option<BoxId> {
        self.parent
    }

    pub fn children(&self) -> &[BoxId] {
        &self.children
    }

    pub fn role(&self) -> BoxGenerationRole {
        self.role
    }

    pub fn kind(&self) -> BoxKind {
        self.kind
    }

    pub fn source(&self) -> BoxSource<'style_tree, 'dom> {
        self.source
    }

    pub fn style(&self) -> &'style_tree ComputedStyle {
        self.style
    }

    pub fn display(&self) -> Display {
        self.display
    }

    pub fn display_behavior(&self) -> DisplayBoxBehavior {
        self.display_behavior
    }

    pub fn containing_block(&self) -> Option<ContainingBlockId> {
        self.containing_block
    }

    pub fn establishes_containing_block(&self) -> bool {
        self.establishes_containing_block
    }

    pub fn formatting_context(&self) -> Option<FormattingContextId> {
        self.formatting_context
    }

    pub fn establishes_formatting_context(&self) -> Option<FormattingContextKind> {
        self.establishes_formatting_context
    }

    pub fn block_formatting_participation(&self) -> BlockFormattingParticipation {
        self.block_formatting_participation
    }

    pub fn list_marker(&self) -> Option<ListMarker> {
        self.list_marker
    }

    pub fn replaced(&self) -> Option<ReplacedKind> {
        self.replaced
    }

    pub fn replaced_intrinsic(&self) -> Option<IntrinsicSize> {
        self.replaced_intrinsic
    }

    pub fn direct_node_id(&self) -> Option<Id> {
        self.source.direct_node_id()
    }

    pub fn anchor_node_id(&self) -> Id {
        self.source.anchor_node_id()
    }
}

/// Explicit generated box tree for one layout pass.
pub struct BoxTree<'style_tree, 'dom> {
    root: BoxId,
    nodes: Vec<BoxNode<'style_tree, 'dom>>,
}

impl fmt::Debug for BoxTree<'_, '_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("BoxTree")
            .field("root", &self.root)
            .field("nodes", &self.nodes)
            .finish()
    }
}

impl<'style_tree, 'dom> BoxTree<'style_tree, 'dom> {
    pub fn generate(
        root: &'style_tree StyledNode<'dom>,
        replaced_info: Option<&dyn ReplacedElementInfoProvider>,
    ) -> Self {
        let mut builder = BoxTreeBuilder { nodes: Vec::new() };
        let root = builder
            .build_styled_subtree(root, None, replaced_info)
            .unwrap_or_else(|| builder.push_fallback_root(root));

        Self {
            root,
            nodes: builder.nodes,
        }
    }

    pub fn root_id(&self) -> BoxId {
        self.root
    }

    pub fn root(&self) -> &BoxNode<'style_tree, 'dom> {
        self.node(self.root)
    }

    pub fn node(&self, id: BoxId) -> &BoxNode<'style_tree, 'dom> {
        &self.nodes[id.index()]
    }

    pub fn nodes(&self) -> &[BoxNode<'style_tree, 'dom>] {
        &self.nodes
    }

    pub fn len(&self) -> usize {
        self.nodes.len()
    }

    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }

    /// Stable debug snapshot for generated box-tree structure.
    pub fn to_debug_snapshot(&self) -> String {
        let mut out = String::new();
        writeln!(&mut out, "version: 1").expect("write snapshot");
        writeln!(&mut out, "box-tree").expect("write snapshot");
        writeln!(&mut out, "root: {}", box_id_debug_label(self.root)).expect("write snapshot");
        writeln!(&mut out, "boxes: {}", self.len()).expect("write snapshot");
        append_box_node_snapshot(&mut out, self, self.root, 0);
        out
    }
}

struct BoxTreeBuilder<'style_tree, 'dom> {
    nodes: Vec<BoxNode<'style_tree, 'dom>>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum AnonymousChildClass {
    InlineLevel,
    BlockLevel,
}

impl<'style_tree, 'dom> BoxTreeBuilder<'style_tree, 'dom> {
    fn build_styled_subtree(
        &mut self,
        styled: &'style_tree StyledNode<'dom>,
        parent: Option<BoxId>,
        replaced_info: Option<&dyn ReplacedElementInfoProvider>,
    ) -> Option<BoxId> {
        let replaced_kind = classify_replaced_kind(styled.node);
        let generation =
            display_box_generation(styled, parent.map(|id| self.node(id).role()), replaced_kind);
        let principal = match generation {
            DisplayBoxGeneration::SuppressSubtree(_) => return None,
            DisplayBoxGeneration::GeneratePrincipalBox(principal) => principal,
        };
        let id = self.push_dom_backed_box(styled, parent, principal, replaced_kind, replaced_info);

        if matches!(styled.node, Node::Document { .. } | Node::Element { .. }) {
            self.build_generated_children(id, styled, replaced_info);
        }

        Some(id)
    }

    fn build_generated_children(
        &mut self,
        parent_id: BoxId,
        styled: &'style_tree StyledNode<'dom>,
        replaced_info: Option<&dyn ReplacedElementInfoProvider>,
    ) {
        let (is_ul, is_ol) = list_container_kind(styled.node);
        let mut next_ol_index: u32 = 1;
        let wrap_inline_runs = self.requires_anonymous_block_wrapping(parent_id, styled);
        let mut current_anonymous_block: Option<BoxId> = None;

        for child in &styled.children {
            let child_class = if wrap_inline_runs {
                self.anonymous_child_class(child, parent_id)
            } else {
                None
            };

            let target_parent = match child_class {
                Some(AnonymousChildClass::InlineLevel) => *current_anonymous_block
                    .get_or_insert_with(|| self.push_anonymous_block_box(parent_id, styled)),
                Some(AnonymousChildClass::BlockLevel) => {
                    current_anonymous_block = None;
                    parent_id
                }
                None => parent_id,
            };

            let Some(child_id) =
                self.build_styled_subtree(child, Some(target_parent), replaced_info)
            else {
                continue;
            };

            if target_parent == parent_id
                && matches!(child.node, Node::Element { .. })
                && self.node(child_id).display_behavior() == DisplayBoxBehavior::ListItem
            {
                if is_ul {
                    self.node_mut(child_id).list_marker = Some(ListMarker::Unordered);
                } else if is_ol {
                    self.node_mut(child_id).list_marker = Some(ListMarker::Ordered(next_ol_index));
                    next_ol_index += 1;
                }
            }

            self.node_mut(target_parent).children.push(child_id);
        }
    }

    fn requires_anonymous_block_wrapping(
        &self,
        parent_id: BoxId,
        styled: &'style_tree StyledNode<'dom>,
    ) -> bool {
        if !supports_anonymous_block_children(self.node(parent_id)) {
            return false;
        }

        let mut has_inline_level = false;
        let mut has_block_level = false;

        for child in &styled.children {
            match self.anonymous_child_class(child, parent_id) {
                Some(AnonymousChildClass::InlineLevel) => has_inline_level = true,
                Some(AnonymousChildClass::BlockLevel) => has_block_level = true,
                None => {}
            }

            if has_inline_level && has_block_level {
                return true;
            }
        }

        false
    }

    fn anonymous_child_class(
        &self,
        child: &'style_tree StyledNode<'dom>,
        parent_id: BoxId,
    ) -> Option<AnonymousChildClass> {
        let replaced_kind = classify_replaced_kind(child.node);
        let generation =
            display_box_generation(child, Some(self.node(parent_id).role()), replaced_kind);
        let principal = match generation {
            DisplayBoxGeneration::SuppressSubtree(_) => return None,
            DisplayBoxGeneration::GeneratePrincipalBox(principal) => principal,
        };

        if principal_participates_inline(principal) {
            Some(AnonymousChildClass::InlineLevel)
        } else {
            Some(AnonymousChildClass::BlockLevel)
        }
    }

    fn push_dom_backed_box(
        &mut self,
        styled: &'style_tree StyledNode<'dom>,
        parent: Option<BoxId>,
        principal: PrincipalBox,
        replaced_kind: Option<ReplacedKind>,
        replaced_info: Option<&dyn ReplacedElementInfoProvider>,
    ) -> BoxId {
        let role = principal.role();
        let kind = principal.kind();
        let replaced = if matches!(kind, BoxKind::ReplacedInline) {
            debug_assert!(replaced_kind.is_some());
            replaced_kind
        } else {
            None
        };
        let replaced_intrinsic = match replaced_kind {
            Some(ReplacedKind::Img) => replaced_info.and_then(|p| p.intrinsic_for_img(styled.node)),
            _ => None,
        };

        let id = BoxId(self.nodes.len());
        self.nodes.push(BoxNode {
            id,
            parent,
            children: Vec::new(),
            role,
            kind,
            source: BoxSource::DomNode(styled),
            style: &styled.style,
            display: styled.style.display(),
            display_behavior: principal.behavior(),
            containing_block: self.containing_block_for_child(parent),
            establishes_containing_block: principal_establishes_containing_block(principal),
            formatting_context: self.formatting_context_for_child(parent),
            establishes_formatting_context: principal_establishes_formatting_context(principal),
            block_formatting_participation: principal_block_formatting_participation(principal),
            list_marker: None,
            replaced,
            replaced_intrinsic,
        });
        id
    }

    fn push_anonymous_block_box(
        &mut self,
        parent: BoxId,
        parent_styled: &'style_tree StyledNode<'dom>,
    ) -> BoxId {
        let id = BoxId(self.nodes.len());
        self.nodes.push(BoxNode {
            id,
            parent: Some(parent),
            children: Vec::new(),
            role: BoxGenerationRole::Anonymous(AnonymousBoxKind::Block),
            kind: BoxKind::Block,
            source: BoxSource::Anonymous {
                parent: parent_styled,
                kind: AnonymousBoxKind::Block,
            },
            style: &parent_styled.style,
            display: Display::Block,
            display_behavior: DisplayBoxBehavior::Anonymous,
            containing_block: self.containing_block_for_child(Some(parent)),
            establishes_containing_block: true,
            formatting_context: self.formatting_context_for_child(Some(parent)),
            establishes_formatting_context: None,
            block_formatting_participation: BlockFormattingParticipation::BlockLevel,
            list_marker: None,
            replaced: None,
            replaced_intrinsic: None,
        });
        self.node_mut(parent).children.push(id);
        id
    }

    fn push_fallback_root(&mut self, styled: &'style_tree StyledNode<'dom>) -> BoxId {
        let id = BoxId(self.nodes.len());
        self.nodes.push(BoxNode {
            id,
            parent: None,
            children: Vec::new(),
            role: BoxGenerationRole::DocumentRoot,
            kind: BoxKind::Block,
            source: BoxSource::DomNode(styled),
            style: &styled.style,
            display: styled.style.display(),
            display_behavior: DisplayBoxBehavior::DocumentRoot,
            containing_block: None,
            establishes_containing_block: true,
            formatting_context: None,
            establishes_formatting_context: Some(FormattingContextKind::Block),
            block_formatting_participation: BlockFormattingParticipation::Root,
            list_marker: None,
            replaced: None,
            replaced_intrinsic: None,
        });
        id
    }

    fn node(&self, id: BoxId) -> &BoxNode<'style_tree, 'dom> {
        &self.nodes[id.index()]
    }

    fn node_mut(&mut self, id: BoxId) -> &mut BoxNode<'style_tree, 'dom> {
        &mut self.nodes[id.index()]
    }

    fn containing_block_for_child(&self, parent: Option<BoxId>) -> Option<ContainingBlockId> {
        let parent = parent?;
        let parent_node = self.node(parent);

        if parent_node.establishes_containing_block() {
            Some(ContainingBlockId(parent))
        } else {
            parent_node.containing_block()
        }
    }

    fn formatting_context_for_child(&self, parent: Option<BoxId>) -> Option<FormattingContextId> {
        let parent = parent?;
        let parent_node = self.node(parent);

        if parent_node.establishes_formatting_context().is_some() {
            Some(FormattingContextId(parent))
        } else {
            parent_node.formatting_context()
        }
    }
}

fn display_box_generation(
    styled: &StyledNode<'_>,
    parent_role: Option<BoxGenerationRole>,
    replaced_kind: Option<ReplacedKind>,
) -> DisplayBoxGeneration {
    if matches!(styled.node, Node::Comment { .. }) {
        return DisplayBoxGeneration::SuppressSubtree(BoxSuppressionReason::CommentNode);
    }

    if matches!(styled.node, Node::Element { .. }) && styled.style.display() == Display::None {
        return DisplayBoxGeneration::SuppressSubtree(BoxSuppressionReason::DisplayNone);
    }

    let role = box_generation_role(styled, parent_role);
    DisplayBoxGeneration::GeneratePrincipalBox(principal_box_for_styled_node(
        styled,
        role,
        replaced_kind,
    ))
}

fn box_generation_role(
    styled: &StyledNode<'_>,
    parent_role: Option<BoxGenerationRole>,
) -> BoxGenerationRole {
    match styled.node {
        Node::Document { .. } => BoxGenerationRole::DocumentRoot,
        Node::Element { .. } => {
            if parent_role == Some(BoxGenerationRole::DocumentRoot) {
                BoxGenerationRole::DocumentElement
            } else {
                BoxGenerationRole::OrdinaryElement
            }
        }
        Node::Text { .. } => BoxGenerationRole::TextRun,
        Node::Comment { .. } => unreachable!("comments do not generate boxes"),
    }
}

fn principal_box_for_styled_node(
    styled: &StyledNode<'_>,
    role: BoxGenerationRole,
    replaced_kind: Option<ReplacedKind>,
) -> PrincipalBox {
    let style = &styled.style;
    let (kind, behavior) = match role {
        BoxGenerationRole::DocumentRoot => (BoxKind::Block, DisplayBoxBehavior::DocumentRoot),
        BoxGenerationRole::DocumentElement => (BoxKind::Block, DisplayBoxBehavior::DocumentElement),
        BoxGenerationRole::TextRun => (BoxKind::Block, DisplayBoxBehavior::TextRun),
        BoxGenerationRole::Anonymous(_) => (BoxKind::Block, DisplayBoxBehavior::Anonymous),
        BoxGenerationRole::Marker => (BoxKind::Block, DisplayBoxBehavior::Marker),
        BoxGenerationRole::OrdinaryElement => {
            if replaced_kind.is_some()
                && matches!(style.display(), Display::Inline | Display::InlineBlock)
            {
                (BoxKind::ReplacedInline, DisplayBoxBehavior::ReplacedInline)
            } else {
                match style.display() {
                    Display::Block => (BoxKind::Block, DisplayBoxBehavior::Block),
                    Display::Inline => (BoxKind::Inline, DisplayBoxBehavior::Inline),
                    Display::InlineBlock => (BoxKind::InlineBlock, DisplayBoxBehavior::InlineBlock),
                    Display::ListItem => (BoxKind::Block, DisplayBoxBehavior::ListItem),
                    Display::None => unreachable!("display:none is suppressed before box creation"),
                }
            }
        }
    };

    PrincipalBox {
        role,
        kind,
        behavior,
    }
}

fn principal_establishes_containing_block(principal: PrincipalBox) -> bool {
    matches!(
        principal.behavior(),
        DisplayBoxBehavior::DocumentRoot
            | DisplayBoxBehavior::DocumentElement
            | DisplayBoxBehavior::Block
            | DisplayBoxBehavior::InlineBlock
            | DisplayBoxBehavior::ListItem
            | DisplayBoxBehavior::Anonymous
    )
}

fn principal_establishes_formatting_context(
    principal: PrincipalBox,
) -> Option<FormattingContextKind> {
    match principal.behavior() {
        DisplayBoxBehavior::DocumentRoot
        | DisplayBoxBehavior::DocumentElement
        | DisplayBoxBehavior::InlineBlock => Some(FormattingContextKind::Block),
        DisplayBoxBehavior::Block
        | DisplayBoxBehavior::ListItem
        | DisplayBoxBehavior::Anonymous
        | DisplayBoxBehavior::Inline
        | DisplayBoxBehavior::TextRun
        | DisplayBoxBehavior::ReplacedInline
        | DisplayBoxBehavior::Marker => None,
    }
}

fn principal_block_formatting_participation(
    principal: PrincipalBox,
) -> BlockFormattingParticipation {
    match principal.behavior() {
        DisplayBoxBehavior::DocumentRoot => BlockFormattingParticipation::Root,
        DisplayBoxBehavior::DocumentElement
        | DisplayBoxBehavior::Block
        | DisplayBoxBehavior::ListItem
        | DisplayBoxBehavior::Anonymous => BlockFormattingParticipation::BlockLevel,
        DisplayBoxBehavior::Inline | DisplayBoxBehavior::TextRun => {
            BlockFormattingParticipation::InlineLevel
        }
        DisplayBoxBehavior::InlineBlock | DisplayBoxBehavior::ReplacedInline => {
            BlockFormattingParticipation::AtomicInline
        }
        DisplayBoxBehavior::Marker => BlockFormattingParticipation::None,
    }
}

fn supports_anonymous_block_children(node: &BoxNode<'_, '_>) -> bool {
    matches!(node.kind(), BoxKind::Block)
        && matches!(
            node.display_behavior(),
            DisplayBoxBehavior::DocumentElement
                | DisplayBoxBehavior::Block
                | DisplayBoxBehavior::ListItem
                | DisplayBoxBehavior::Anonymous
        )
}

fn principal_participates_inline(principal: PrincipalBox) -> bool {
    matches!(
        principal.behavior(),
        DisplayBoxBehavior::Inline
            | DisplayBoxBehavior::InlineBlock
            | DisplayBoxBehavior::TextRun
            | DisplayBoxBehavior::ReplacedInline
    )
}

fn list_container_kind(node: &Node) -> (bool, bool) {
    match node {
        Node::Element { name, .. } => {
            let is_ul = name.eq_ignore_ascii_case("ul");
            let is_ol = name.eq_ignore_ascii_case("ol");
            (is_ul, is_ol)
        }
        _ => (false, false),
    }
}

fn append_box_node_snapshot(out: &mut String, tree: &BoxTree<'_, '_>, id: BoxId, depth: usize) {
    let node = tree.node(id);
    let indent = "  ".repeat(depth);
    writeln!(
        out,
        "{indent}{}: parent={} cb={} establishes-cb={} fc={} establishes-fc={} block-participation={} source-id={} source={} role={} kind={} display={} behavior={} children={} marker={} replaced={} intrinsic={}",
        box_id_debug_label(node.id),
        optional_box_id_debug_label(node.parent),
        optional_containing_block_id_debug_label(node.containing_block),
        bool_debug_label(node.establishes_containing_block),
        optional_formatting_context_id_debug_label(node.formatting_context),
        optional_formatting_context_kind_debug_label(node.establishes_formatting_context),
        block_formatting_participation_debug_label(node.block_formatting_participation),
        optional_node_id_debug_label(node.direct_node_id()),
        node_debug_label(node.source.anchor_styled_node().node),
        role_debug_label(node.role),
        box_kind_debug_label(node.kind),
        display_debug_label(node.display),
        display_behavior_debug_label(node.display_behavior),
        children_debug_label(&node.children),
        list_marker_debug_label(node.list_marker),
        replaced_kind_debug_label(node.replaced),
        intrinsic_size_debug_label(node.replaced_intrinsic),
    )
    .expect("write snapshot");

    for child in &node.children {
        append_box_node_snapshot(out, tree, *child, depth + 1);
    }
}

fn box_id_debug_label(id: BoxId) -> String {
    format!("b{}", id.index())
}

fn optional_box_id_debug_label(id: Option<BoxId>) -> String {
    id.map(box_id_debug_label)
        .unwrap_or_else(|| "none".to_string())
}

fn optional_containing_block_id_debug_label(id: Option<ContainingBlockId>) -> String {
    id.map(|id| box_id_debug_label(id.box_id()))
        .unwrap_or_else(|| "none".to_string())
}

fn optional_formatting_context_id_debug_label(id: Option<FormattingContextId>) -> String {
    id.map(|id| box_id_debug_label(id.box_id()))
        .unwrap_or_else(|| "none".to_string())
}

fn optional_formatting_context_kind_debug_label(
    kind: Option<FormattingContextKind>,
) -> &'static str {
    match kind {
        Some(FormattingContextKind::Block) => "block",
        None => "none",
    }
}

fn block_formatting_participation_debug_label(
    participation: BlockFormattingParticipation,
) -> &'static str {
    match participation {
        BlockFormattingParticipation::Root => "root",
        BlockFormattingParticipation::BlockLevel => "block-level",
        BlockFormattingParticipation::InlineLevel => "inline-level",
        BlockFormattingParticipation::AtomicInline => "atomic-inline",
        BlockFormattingParticipation::None => "none",
    }
}

fn optional_node_id_debug_label(id: Option<Id>) -> String {
    id.map(|id| id.0.to_string())
        .unwrap_or_else(|| "none".to_string())
}

fn bool_debug_label(value: bool) -> &'static str {
    if value { "yes" } else { "no" }
}

fn children_debug_label(children: &[BoxId]) -> String {
    let mut out = String::from("[");
    for (index, child) in children.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        out.push_str(&box_id_debug_label(*child));
    }
    out.push(']');
    out
}

fn role_debug_label(role: BoxGenerationRole) -> &'static str {
    match role {
        BoxGenerationRole::DocumentRoot => "document-root",
        BoxGenerationRole::DocumentElement => "document-element",
        BoxGenerationRole::OrdinaryElement => "ordinary-element",
        BoxGenerationRole::TextRun => "text-run",
        BoxGenerationRole::Anonymous(AnonymousBoxKind::Block) => "anonymous-block",
        BoxGenerationRole::Anonymous(AnonymousBoxKind::Inline) => "anonymous-inline",
        BoxGenerationRole::Marker => "marker",
    }
}

fn display_debug_label(display: Display) -> &'static str {
    match display {
        Display::Block => "block",
        Display::Inline => "inline",
        Display::InlineBlock => "inline-block",
        Display::ListItem => "list-item",
        Display::None => "none",
    }
}

fn display_behavior_debug_label(behavior: DisplayBoxBehavior) -> &'static str {
    match behavior {
        DisplayBoxBehavior::DocumentRoot => "document-root",
        DisplayBoxBehavior::DocumentElement => "document-element",
        DisplayBoxBehavior::Block => "block",
        DisplayBoxBehavior::Inline => "inline",
        DisplayBoxBehavior::InlineBlock => "inline-block",
        DisplayBoxBehavior::ListItem => "list-item",
        DisplayBoxBehavior::TextRun => "text-run",
        DisplayBoxBehavior::ReplacedInline => "replaced-inline",
        DisplayBoxBehavior::Anonymous => "anonymous",
        DisplayBoxBehavior::Marker => "marker",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use css::Length;
    use html::Node;
    use html::internal::Id;
    use std::sync::Arc;

    struct TestMeasurer;

    impl crate::TextMeasurer for TestMeasurer {
        fn measure(&self, text: &str, style: &ComputedStyle) -> f32 {
            let Length::Px(font_px) = style.font_size();
            text.chars().count() as f32 * font_px * 0.5
        }

        fn line_height(&self, style: &ComputedStyle) -> f32 {
            let Length::Px(font_px) = style.font_size();
            font_px * 1.2
        }
    }

    fn element(id: u32, name: &str, style: Vec<(&str, &str)>, children: Vec<Node>) -> Node {
        Node::Element {
            id: Id(id),
            name: Arc::from(name),
            attributes: Vec::new(),
            style: style
                .into_iter()
                .map(|(property, value)| (property.to_string(), value.to_string()))
                .collect(),
            children,
        }
    }

    fn text(id: u32, value: &str) -> Node {
        Node::Text {
            id: Id(id),
            text: value.to_string(),
        }
    }

    fn comment(id: u32, value: &str) -> Node {
        Node::Comment {
            id: Id(id),
            text: value.to_string(),
        }
    }

    fn doc(children: Vec<Node>) -> Node {
        Node::Document {
            id: Id(1),
            doctype: None,
            children,
        }
    }

    fn source_ids(tree: &BoxTree<'_, '_>) -> Vec<Option<Id>> {
        tree.nodes()
            .iter()
            .map(|node| node.direct_node_id())
            .collect()
    }

    fn box_by_node_id<'tree, 'style_tree, 'dom>(
        tree: &'tree BoxTree<'style_tree, 'dom>,
        id: Id,
    ) -> &'tree BoxNode<'style_tree, 'dom> {
        tree.nodes()
            .iter()
            .find(|node| node.direct_node_id() == Some(id))
            .unwrap_or_else(|| panic!("expected box for node id {id:?}"))
    }

    fn containing_block_box_id(node: &BoxNode<'_, '_>) -> Option<BoxId> {
        node.containing_block().map(ContainingBlockId::box_id)
    }

    fn formatting_context_box_id(node: &BoxNode<'_, '_>) -> Option<BoxId> {
        node.formatting_context().map(FormattingContextId::box_id)
    }

    fn anonymous_boxes<'tree, 'style_tree, 'dom>(
        tree: &'tree BoxTree<'style_tree, 'dom>,
    ) -> Vec<&'tree BoxNode<'style_tree, 'dom>> {
        tree.nodes()
            .iter()
            .filter(|node| matches!(node.role(), BoxGenerationRole::Anonymous(_)))
            .collect()
    }

    fn find_layout_by_direct_node_id<'layout, 'style_tree, 'dom>(
        layout: &'layout crate::LayoutBox<'style_tree, 'dom>,
        id: Id,
    ) -> Option<&'layout crate::LayoutBox<'style_tree, 'dom>> {
        if layout.direct_node_id() == Some(id) {
            return Some(layout);
        }

        layout
            .children
            .iter()
            .find_map(|child| find_layout_by_direct_node_id(child, id))
    }

    #[test]
    fn box_tree_records_parent_child_links_in_deterministic_preorder() {
        let dom = doc(vec![element(
            2,
            "html",
            Vec::new(),
            vec![element(
                3,
                "body",
                Vec::new(),
                vec![element(
                    4,
                    "div",
                    Vec::new(),
                    vec![element(5, "span", Vec::new(), vec![text(6, "hello")])],
                )],
            )],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        assert_eq!(tree.root_id(), BoxId(0));
        assert_eq!(
            source_ids(&tree),
            vec![
                Some(Id(1)),
                Some(Id(2)),
                Some(Id(3)),
                Some(Id(4)),
                Some(Id(5)),
                Some(Id(6)),
            ]
        );

        for node in tree.nodes() {
            for child in node.children() {
                assert_eq!(tree.node(*child).parent(), Some(node.id()));
            }
        }

        assert_eq!(tree.node(BoxId(0)).children(), &[BoxId(1)]);
        assert_eq!(
            tree.node(BoxId(1)).role(),
            BoxGenerationRole::DocumentElement
        );
        assert_eq!(tree.node(BoxId(5)).role(), BoxGenerationRole::TextRun);
    }

    #[test]
    fn nested_html_element_is_not_classified_as_document_element() {
        let dom = doc(vec![element(
            2,
            "html",
            Vec::new(),
            vec![element(
                3,
                "body",
                Vec::new(),
                vec![element(4, "html", Vec::new(), Vec::new())],
            )],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        assert_eq!(
            tree.node(BoxId(1)).role(),
            BoxGenerationRole::DocumentElement
        );

        let nested_html = tree
            .nodes()
            .iter()
            .find(|node| node.direct_node_id() == Some(Id(4)))
            .expect("nested html box");
        assert_eq!(nested_html.role(), BoxGenerationRole::OrdinaryElement);
    }

    #[test]
    fn display_none_subtrees_are_omitted_from_box_tree() {
        let dom = doc(vec![element(
            2,
            "div",
            Vec::new(),
            vec![
                element(
                    3,
                    "span",
                    vec![("display", "none")],
                    vec![text(4, "hidden")],
                ),
                element(5, "span", Vec::new(), vec![text(6, "visible")]),
            ],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        assert_eq!(
            source_ids(&tree),
            vec![Some(Id(1)), Some(Id(2)), Some(Id(5)), Some(Id(6))]
        );
        assert!(
            tree.nodes()
                .iter()
                .all(|node| node.direct_node_id() != Some(Id(3)))
        );
        assert!(
            tree.nodes()
                .iter()
                .all(|node| node.direct_node_id() != Some(Id(4)))
        );
    }

    #[test]
    fn comments_do_not_generate_layout_boxes() {
        let dom = doc(vec![element(
            2,
            "div",
            Vec::new(),
            vec![comment(3, "ignored"), text(4, "visible")],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        assert_eq!(
            source_ids(&tree),
            vec![Some(Id(1)), Some(Id(2)), Some(Id(4))]
        );
        assert!(
            tree.nodes()
                .iter()
                .all(|node| node.direct_node_id() != Some(Id(3)))
        );
    }

    #[test]
    fn containing_blocks_are_assigned_for_current_flow_subset() {
        let dom = doc(vec![element(
            2,
            "html",
            Vec::new(),
            vec![element(
                3,
                "body",
                vec![("display", "block")],
                vec![element(
                    4,
                    "div",
                    vec![("display", "block")],
                    vec![
                        element(5, "span", Vec::new(), vec![text(6, "inline")]),
                        element(
                            7,
                            "span",
                            vec![("display", "inline-block")],
                            vec![text(8, "inline-block child")],
                        ),
                    ],
                )],
            )],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        let document = tree.node(BoxId(0));
        let html = box_by_node_id(&tree, Id(2));
        let body = box_by_node_id(&tree, Id(3));
        let div = box_by_node_id(&tree, Id(4));
        let inline_span = box_by_node_id(&tree, Id(5));
        let inline_text = box_by_node_id(&tree, Id(6));
        let inline_block = box_by_node_id(&tree, Id(7));
        let inline_block_text = box_by_node_id(&tree, Id(8));

        assert_eq!(containing_block_box_id(document), None);
        assert!(document.establishes_containing_block());

        assert_eq!(containing_block_box_id(html), Some(document.id()));
        assert!(html.establishes_containing_block());

        assert_eq!(containing_block_box_id(body), Some(html.id()));
        assert!(body.establishes_containing_block());

        assert_eq!(containing_block_box_id(div), Some(body.id()));
        assert!(div.establishes_containing_block());

        assert_eq!(containing_block_box_id(inline_span), Some(div.id()));
        assert!(!inline_span.establishes_containing_block());

        assert_eq!(containing_block_box_id(inline_text), Some(div.id()));
        assert!(!inline_text.establishes_containing_block());

        assert_eq!(containing_block_box_id(inline_block), Some(div.id()));
        assert!(inline_block.establishes_containing_block());

        assert_eq!(
            containing_block_box_id(inline_block_text),
            Some(inline_block.id())
        );
        assert!(!inline_block_text.establishes_containing_block());
    }

    #[test]
    fn block_formatting_contexts_are_assigned_for_current_flow_subset() {
        let dom = doc(vec![element(
            2,
            "html",
            Vec::new(),
            vec![element(
                3,
                "body",
                vec![("display", "block")],
                vec![element(
                    4,
                    "div",
                    vec![("display", "block")],
                    vec![
                        element(5, "span", Vec::new(), vec![text(6, "inline")]),
                        element(
                            7,
                            "span",
                            vec![("display", "inline-block")],
                            vec![text(8, "inline-block child")],
                        ),
                    ],
                )],
            )],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        let document = tree.node(BoxId(0));
        let html = box_by_node_id(&tree, Id(2));
        let body = box_by_node_id(&tree, Id(3));
        let div = box_by_node_id(&tree, Id(4));
        let inline_span = box_by_node_id(&tree, Id(5));
        let inline_text = box_by_node_id(&tree, Id(6));
        let inline_block = box_by_node_id(&tree, Id(7));
        let inline_block_text = box_by_node_id(&tree, Id(8));

        assert_eq!(formatting_context_box_id(document), None);
        assert_eq!(
            document.establishes_formatting_context(),
            Some(FormattingContextKind::Block)
        );
        assert_eq!(
            document.block_formatting_participation(),
            BlockFormattingParticipation::Root
        );

        assert_eq!(formatting_context_box_id(html), Some(document.id()));
        assert_eq!(
            html.establishes_formatting_context(),
            Some(FormattingContextKind::Block)
        );
        assert_eq!(
            html.block_formatting_participation(),
            BlockFormattingParticipation::BlockLevel
        );

        assert_eq!(formatting_context_box_id(body), Some(html.id()));
        assert_eq!(body.establishes_formatting_context(), None);
        assert_eq!(
            body.block_formatting_participation(),
            BlockFormattingParticipation::BlockLevel
        );

        assert_eq!(formatting_context_box_id(div), Some(html.id()));
        assert_eq!(div.establishes_formatting_context(), None);
        assert_eq!(
            div.block_formatting_participation(),
            BlockFormattingParticipation::BlockLevel
        );

        assert_eq!(formatting_context_box_id(inline_span), Some(html.id()));
        assert_eq!(inline_span.establishes_formatting_context(), None);
        assert_eq!(
            inline_span.block_formatting_participation(),
            BlockFormattingParticipation::InlineLevel
        );

        assert_eq!(formatting_context_box_id(inline_text), Some(html.id()));
        assert_eq!(inline_text.establishes_formatting_context(), None);
        assert_eq!(
            inline_text.block_formatting_participation(),
            BlockFormattingParticipation::InlineLevel
        );

        assert_eq!(formatting_context_box_id(inline_block), Some(html.id()));
        assert_eq!(
            inline_block.establishes_formatting_context(),
            Some(FormattingContextKind::Block)
        );
        assert_eq!(
            inline_block.block_formatting_participation(),
            BlockFormattingParticipation::AtomicInline
        );

        assert_eq!(
            formatting_context_box_id(inline_block_text),
            Some(inline_block.id())
        );
        assert_eq!(inline_block_text.establishes_formatting_context(), None);
        assert_eq!(
            inline_block_text.block_formatting_participation(),
            BlockFormattingParticipation::InlineLevel
        );
    }

    #[test]
    fn anonymous_blocks_establish_containing_blocks_for_wrapped_inline_runs() {
        let dom = doc(vec![element(
            2,
            "div",
            Vec::new(),
            vec![
                text(3, "before"),
                element(4, "p", Vec::new(), vec![text(5, "block")]),
            ],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        let div = box_by_node_id(&tree, Id(2));
        let anonymous = tree.node(div.children()[0]);
        let wrapped_text = box_by_node_id(&tree, Id(3));
        let paragraph = box_by_node_id(&tree, Id(4));
        let paragraph_text = box_by_node_id(&tree, Id(5));

        assert_eq!(containing_block_box_id(anonymous), Some(div.id()));
        assert!(anonymous.establishes_containing_block());

        assert_eq!(containing_block_box_id(wrapped_text), Some(anonymous.id()));
        assert!(!wrapped_text.establishes_containing_block());

        assert_eq!(containing_block_box_id(paragraph), Some(div.id()));
        assert!(paragraph.establishes_containing_block());

        assert_eq!(
            containing_block_box_id(paragraph_text),
            Some(paragraph.id())
        );
        assert!(!paragraph_text.establishes_containing_block());
    }

    #[test]
    fn anonymous_blocks_participate_without_establishing_block_formatting_contexts() {
        let dom = doc(vec![element(
            2,
            "div",
            Vec::new(),
            vec![
                text(3, "before"),
                element(4, "p", Vec::new(), vec![text(5, "block")]),
            ],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        let document_element = box_by_node_id(&tree, Id(2));
        let anonymous = tree.node(document_element.children()[0]);
        let wrapped_text = box_by_node_id(&tree, Id(3));
        let paragraph = box_by_node_id(&tree, Id(4));
        let paragraph_text = box_by_node_id(&tree, Id(5));

        assert_eq!(
            formatting_context_box_id(anonymous),
            Some(document_element.id())
        );
        assert_eq!(anonymous.establishes_formatting_context(), None);
        assert_eq!(
            anonymous.block_formatting_participation(),
            BlockFormattingParticipation::BlockLevel
        );

        assert_eq!(
            formatting_context_box_id(wrapped_text),
            Some(document_element.id())
        );
        assert_eq!(wrapped_text.establishes_formatting_context(), None);
        assert_eq!(
            wrapped_text.block_formatting_participation(),
            BlockFormattingParticipation::InlineLevel
        );

        assert_eq!(
            formatting_context_box_id(paragraph),
            Some(document_element.id())
        );
        assert_eq!(paragraph.establishes_formatting_context(), None);
        assert_eq!(
            paragraph.block_formatting_participation(),
            BlockFormattingParticipation::BlockLevel
        );

        assert_eq!(
            formatting_context_box_id(paragraph_text),
            Some(document_element.id())
        );
        assert_eq!(paragraph_text.establishes_formatting_context(), None);
    }

    #[test]
    fn list_items_participate_without_establishing_block_formatting_contexts() {
        let dom = doc(vec![element(
            2,
            "html",
            Vec::new(),
            vec![element(
                3,
                "body",
                Vec::new(),
                vec![element(
                    4,
                    "ul",
                    Vec::new(),
                    vec![element(
                        5,
                        "li",
                        vec![("display", "list-item")],
                        vec![text(6, "item")],
                    )],
                )],
            )],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        let html = box_by_node_id(&tree, Id(2));
        let list = box_by_node_id(&tree, Id(4));
        let item = box_by_node_id(&tree, Id(5));
        let item_text = box_by_node_id(&tree, Id(6));

        assert_eq!(formatting_context_box_id(list), Some(html.id()));
        assert_eq!(list.establishes_formatting_context(), None);
        assert_eq!(
            list.block_formatting_participation(),
            BlockFormattingParticipation::BlockLevel
        );

        assert_eq!(formatting_context_box_id(item), Some(html.id()));
        assert_eq!(item.establishes_formatting_context(), None);
        assert_eq!(
            item.block_formatting_participation(),
            BlockFormattingParticipation::BlockLevel
        );
        assert_eq!(item.display_behavior(), DisplayBoxBehavior::ListItem);

        assert_eq!(formatting_context_box_id(item_text), Some(html.id()));
        assert_eq!(item_text.establishes_formatting_context(), None);
        assert_eq!(
            item_text.block_formatting_participation(),
            BlockFormattingParticipation::InlineLevel
        );
    }

    #[test]
    fn mixed_inline_and_block_children_generate_anonymous_block_runs() {
        let dom = doc(vec![element(
            2,
            "div",
            Vec::new(),
            vec![
                text(3, "before"),
                element(4, "span", Vec::new(), vec![text(5, "inline")]),
                element(6, "p", Vec::new(), vec![text(7, "block")]),
                text(8, "after"),
            ],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        assert_eq!(
            source_ids(&tree),
            vec![
                Some(Id(1)),
                Some(Id(2)),
                None,
                Some(Id(3)),
                Some(Id(4)),
                Some(Id(5)),
                Some(Id(6)),
                Some(Id(7)),
                None,
                Some(Id(8)),
            ]
        );

        let div = box_by_node_id(&tree, Id(2));
        assert_eq!(div.children(), &[BoxId(2), BoxId(6), BoxId(8)]);

        let first_anonymous = tree.node(BoxId(2));
        assert_eq!(
            first_anonymous.role(),
            BoxGenerationRole::Anonymous(AnonymousBoxKind::Block)
        );
        assert_eq!(first_anonymous.kind(), BoxKind::Block);
        assert_eq!(
            first_anonymous.display_behavior(),
            DisplayBoxBehavior::Anonymous
        );
        assert_eq!(first_anonymous.display(), Display::Block);
        assert_eq!(first_anonymous.direct_node_id(), None);
        assert_eq!(first_anonymous.anchor_node_id(), Id(2));
        assert_eq!(first_anonymous.children(), &[BoxId(3), BoxId(4)]);
        assert_eq!(tree.node(BoxId(3)).parent(), Some(BoxId(2)));
        assert_eq!(tree.node(BoxId(4)).parent(), Some(BoxId(2)));

        let second_anonymous = tree.node(BoxId(8));
        assert_eq!(
            second_anonymous.role(),
            BoxGenerationRole::Anonymous(AnonymousBoxKind::Block)
        );
        assert_eq!(second_anonymous.children(), &[BoxId(9)]);
        assert_eq!(tree.node(BoxId(9)).parent(), Some(BoxId(8)));
    }

    #[test]
    fn all_inline_children_do_not_generate_anonymous_block_boxes() {
        let dom = doc(vec![element(
            2,
            "div",
            Vec::new(),
            vec![
                text(3, "before"),
                element(4, "span", Vec::new(), vec![text(5, "inline")]),
                element(6, "input", Vec::new(), Vec::new()),
            ],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        assert!(anonymous_boxes(&tree).is_empty());
        assert_eq!(
            box_by_node_id(&tree, Id(2)).children(),
            &[BoxId(2), BoxId(3), BoxId(5)]
        );
    }

    #[test]
    fn all_block_children_do_not_generate_anonymous_block_boxes() {
        let dom = doc(vec![element(
            2,
            "div",
            Vec::new(),
            vec![
                element(3, "p", Vec::new(), vec![text(4, "one")]),
                element(5, "section", Vec::new(), vec![text(6, "two")]),
            ],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        assert!(anonymous_boxes(&tree).is_empty());
        assert_eq!(
            box_by_node_id(&tree, Id(2)).children(),
            &[BoxId(2), BoxId(4)]
        );
    }

    #[test]
    fn layout_projection_accepts_anonymous_boxes_as_layout_participants() {
        let dom = doc(vec![element(
            2,
            "div",
            Vec::new(),
            vec![
                text(3, "before"),
                element(4, "p", Vec::new(), vec![text(5, "block")]),
                text(6, "after"),
            ],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let layout = crate::layout_block_tree(&styled, 500.0, &TestMeasurer, None);
        let div = find_layout_by_direct_node_id(&layout, Id(2)).expect("div layout box");

        assert_eq!(div.children.len(), 3);
        assert!(div.children[0].is_anonymous());
        assert_eq!(div.children[0].direct_node_id(), None);
        assert_eq!(div.children[0].node_id(), Id(2));
        assert_eq!(div.children[0].children[0].direct_node_id(), Some(Id(3)));
        assert_eq!(div.children[1].direct_node_id(), Some(Id(4)));
        assert!(div.children[2].is_anonymous());
        assert_eq!(div.children[2].children[0].direct_node_id(), Some(Id(6)));
    }

    #[test]
    fn layout_projection_preserves_containing_block_metadata() {
        let dom = doc(vec![element(
            2,
            "div",
            Vec::new(),
            vec![
                element(3, "span", Vec::new(), vec![text(4, "inline")]),
                element(
                    5,
                    "span",
                    vec![("display", "inline-block")],
                    vec![text(6, "atomic")],
                ),
            ],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let layout = crate::layout_block_tree(&styled, 500.0, &TestMeasurer, None);

        let div = find_layout_by_direct_node_id(&layout, Id(2)).expect("div layout box");
        let inline_span =
            find_layout_by_direct_node_id(&layout, Id(3)).expect("inline span layout box");
        let inline_text =
            find_layout_by_direct_node_id(&layout, Id(4)).expect("inline text layout box");
        let inline_block =
            find_layout_by_direct_node_id(&layout, Id(5)).expect("inline-block layout box");
        let inline_block_text =
            find_layout_by_direct_node_id(&layout, Id(6)).expect("inline-block text layout box");

        assert!(div.establishes_containing_block());

        assert_eq!(
            inline_span
                .containing_block()
                .map(ContainingBlockId::box_id),
            Some(div.box_id())
        );
        assert!(!inline_span.establishes_containing_block());

        assert_eq!(
            inline_text
                .containing_block()
                .map(ContainingBlockId::box_id),
            Some(div.box_id())
        );
        assert!(!inline_text.establishes_containing_block());

        assert_eq!(
            inline_block
                .containing_block()
                .map(ContainingBlockId::box_id),
            Some(div.box_id())
        );
        assert!(inline_block.establishes_containing_block());

        assert_eq!(
            inline_block_text
                .containing_block()
                .map(ContainingBlockId::box_id),
            Some(inline_block.box_id())
        );
        assert!(!inline_block_text.establishes_containing_block());
    }

    #[test]
    fn layout_projection_preserves_block_formatting_context_metadata() {
        let dom = doc(vec![element(
            2,
            "html",
            Vec::new(),
            vec![element(
                3,
                "body",
                Vec::new(),
                vec![element(
                    4,
                    "div",
                    Vec::new(),
                    vec![
                        element(5, "span", Vec::new(), vec![text(6, "inline")]),
                        element(
                            7,
                            "span",
                            vec![("display", "inline-block")],
                            vec![text(8, "atomic")],
                        ),
                    ],
                )],
            )],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let layout = crate::layout_block_tree(&styled, 500.0, &TestMeasurer, None);

        let html = find_layout_by_direct_node_id(&layout, Id(2)).expect("html layout box");
        let div = find_layout_by_direct_node_id(&layout, Id(4)).expect("div layout box");
        let inline_span =
            find_layout_by_direct_node_id(&layout, Id(5)).expect("inline span layout box");
        let inline_text =
            find_layout_by_direct_node_id(&layout, Id(6)).expect("inline text layout box");
        let inline_block =
            find_layout_by_direct_node_id(&layout, Id(7)).expect("inline-block layout box");
        let inline_block_text =
            find_layout_by_direct_node_id(&layout, Id(8)).expect("inline-block text layout box");

        assert_eq!(
            html.establishes_formatting_context(),
            Some(FormattingContextKind::Block)
        );

        assert_eq!(
            div.formatting_context().map(FormattingContextId::box_id),
            Some(html.box_id())
        );
        assert_eq!(div.establishes_formatting_context(), None);
        assert_eq!(
            div.block_formatting_participation(),
            BlockFormattingParticipation::BlockLevel
        );

        assert_eq!(
            inline_span
                .formatting_context()
                .map(FormattingContextId::box_id),
            Some(html.box_id())
        );
        assert_eq!(inline_span.establishes_formatting_context(), None);
        assert_eq!(
            inline_span.block_formatting_participation(),
            BlockFormattingParticipation::InlineLevel
        );

        assert_eq!(
            inline_text
                .formatting_context()
                .map(FormattingContextId::box_id),
            Some(html.box_id())
        );
        assert_eq!(inline_text.establishes_formatting_context(), None);

        assert_eq!(
            inline_block
                .formatting_context()
                .map(FormattingContextId::box_id),
            Some(html.box_id())
        );
        assert_eq!(
            inline_block.establishes_formatting_context(),
            Some(FormattingContextKind::Block)
        );
        assert_eq!(
            inline_block.block_formatting_participation(),
            BlockFormattingParticipation::AtomicInline
        );

        assert_eq!(
            inline_block_text
                .formatting_context()
                .map(FormattingContextId::box_id),
            Some(inline_block.box_id())
        );
        assert_eq!(inline_block_text.establishes_formatting_context(), None);
    }

    #[test]
    fn layout_debug_snapshot_distinguishes_anonymous_box_sources() {
        let dom = doc(vec![element(
            2,
            "div",
            Vec::new(),
            vec![
                text(3, "before"),
                element(4, "p", Vec::new(), vec![text(5, "block")]),
            ],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let output = crate::layout_document(crate::LayoutPhaseInput::new(
            &styled,
            500.0,
            &TestMeasurer,
            None,
        ));
        let snapshot = output.to_debug_snapshot();

        assert!(
            snapshot.contains("source=anonymous-block(anchor=2) node=element(\"div\") kind=block")
        );
        assert!(snapshot.contains("source=dom(3) node=text(\"before\")"));
        assert!(snapshot.contains("source=dom(4) node=element(\"p\")"));
    }

    #[test]
    fn supported_display_values_map_to_principal_box_behavior() {
        let dom = doc(vec![element(
            2,
            "html",
            Vec::new(),
            vec![element(
                3,
                "body",
                Vec::new(),
                vec![
                    element(4, "div", vec![("display", "block")], Vec::new()),
                    element(5, "span", vec![("display", "inline")], Vec::new()),
                    element(6, "span", vec![("display", "inline-block")], Vec::new()),
                    element(7, "li", vec![("display", "list-item")], Vec::new()),
                    element(8, "span", vec![("display", "none")], Vec::new()),
                    element(9, "input", vec![("display", "inline-block")], Vec::new()),
                ],
            )],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        assert_eq!(
            box_by_node_id(&tree, Id(1)).display_behavior(),
            DisplayBoxBehavior::DocumentRoot
        );
        assert_eq!(
            box_by_node_id(&tree, Id(2)).display_behavior(),
            DisplayBoxBehavior::DocumentElement
        );

        let block = box_by_node_id(&tree, Id(4));
        assert_eq!(block.kind(), BoxKind::Block);
        assert_eq!(block.display(), Display::Block);
        assert_eq!(block.display_behavior(), DisplayBoxBehavior::Block);

        let inline = box_by_node_id(&tree, Id(5));
        assert_eq!(inline.kind(), BoxKind::Inline);
        assert_eq!(inline.display(), Display::Inline);
        assert_eq!(inline.display_behavior(), DisplayBoxBehavior::Inline);

        let inline_block = box_by_node_id(&tree, Id(6));
        assert_eq!(inline_block.kind(), BoxKind::InlineBlock);
        assert_eq!(inline_block.display(), Display::InlineBlock);
        assert_eq!(
            inline_block.display_behavior(),
            DisplayBoxBehavior::InlineBlock
        );

        let list_item = box_by_node_id(&tree, Id(7));
        assert_eq!(list_item.kind(), BoxKind::Block);
        assert_eq!(list_item.display(), Display::ListItem);
        assert_eq!(list_item.display_behavior(), DisplayBoxBehavior::ListItem);

        assert!(
            tree.nodes()
                .iter()
                .all(|node| node.direct_node_id() != Some(Id(8)))
        );

        let input = box_by_node_id(&tree, Id(9));
        assert_eq!(input.kind(), BoxKind::ReplacedInline);
        assert_eq!(input.display(), Display::InlineBlock);
        assert_eq!(input.display_behavior(), DisplayBoxBehavior::ReplacedInline);
        assert_eq!(input.replaced(), Some(ReplacedKind::InputText));
    }

    #[test]
    fn unsupported_display_keywords_do_not_reach_box_generation_as_deferred_modes() {
        let dom = doc(vec![element(
            2,
            "html",
            Vec::new(),
            vec![element(
                3,
                "body",
                Vec::new(),
                vec![element(4, "span", vec![("display", "flex")], Vec::new())],
            )],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        let unsupported = box_by_node_id(&tree, Id(4));
        assert_eq!(unsupported.display(), Display::Inline);
        assert_eq!(unsupported.kind(), BoxKind::Inline);
        assert_eq!(unsupported.display_behavior(), DisplayBoxBehavior::Inline);
    }

    #[test]
    fn list_item_marker_metadata_is_assigned_from_box_tree_parent_context() {
        let dom = doc(vec![
            element(
                2,
                "ul",
                Vec::new(),
                vec![
                    element(3, "li", Vec::new(), vec![text(4, "a")]),
                    element(5, "li", Vec::new(), vec![text(6, "b")]),
                ],
            ),
            element(
                7,
                "ol",
                Vec::new(),
                vec![
                    element(8, "li", Vec::new(), vec![text(9, "one")]),
                    element(10, "li", Vec::new(), vec![text(11, "two")]),
                ],
            ),
        ]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        let markers = tree
            .nodes()
            .iter()
            .filter_map(|node| {
                node.list_marker()
                    .map(|marker| (node.direct_node_id(), marker))
            })
            .collect::<Vec<_>>();
        assert_eq!(
            markers,
            vec![
                (Some(Id(3)), ListMarker::Unordered),
                (Some(Id(5)), ListMarker::Unordered),
                (Some(Id(8)), ListMarker::Ordered(1)),
                (Some(Id(10)), ListMarker::Ordered(2)),
            ]
        );
    }

    #[test]
    fn list_marker_assignment_uses_display_box_behavior() {
        let dom = doc(vec![element(
            2,
            "ul",
            Vec::new(),
            vec![element(3, "li", vec![("display", "list-item")], Vec::new())],
        )]);

        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);
        let item = box_by_node_id(&tree, Id(3));

        assert_eq!(item.display(), Display::ListItem);
        assert_eq!(item.display_behavior(), DisplayBoxBehavior::ListItem);
        assert_eq!(item.list_marker(), Some(ListMarker::Unordered));
    }

    #[test]
    fn box_tree_stores_layout_metadata_without_dom_parent_ownership() {
        let dom = doc(vec![element(
            2,
            "div",
            Vec::new(),
            vec![
                element(3, "span", vec![("display", "inline-block")], Vec::new()),
                element(4, "input", Vec::new(), Vec::new()),
            ],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        let inline_block = tree
            .nodes()
            .iter()
            .find(|node| node.direct_node_id() == Some(Id(3)))
            .expect("inline-block box");
        assert_eq!(inline_block.kind(), BoxKind::InlineBlock);
        assert_eq!(
            inline_block.display_behavior(),
            DisplayBoxBehavior::InlineBlock
        );
        assert_eq!(inline_block.parent(), Some(BoxId(1)));
        assert_eq!(inline_block.source().direct_node_id(), Some(Id(3)));

        let input = tree
            .nodes()
            .iter()
            .find(|node| node.direct_node_id() == Some(Id(4)))
            .expect("input box");
        assert_eq!(input.replaced(), Some(ReplacedKind::InputText));
        assert_eq!(input.kind(), BoxKind::ReplacedInline);
        assert_eq!(input.display_behavior(), DisplayBoxBehavior::ReplacedInline);
        assert_eq!(input.parent(), Some(BoxId(1)));
    }

    #[test]
    fn box_tree_debug_snapshot_is_stable_and_structural() {
        let dom = doc(vec![element(
            2,
            "div",
            Vec::new(),
            vec![element(3, "span", Vec::new(), vec![text(4, "x")])],
        )]);
        let styled = css::build_style_tree(&dom, None);
        let tree = BoxTree::generate(&styled, None);

        assert_eq!(
            tree.to_debug_snapshot(),
            concat!(
                "version: 1\n",
                "box-tree\n",
                "root: b0\n",
                "boxes: 4\n",
                "b0: parent=none cb=none establishes-cb=yes fc=none establishes-fc=block block-participation=root source-id=1 source=document role=document-root kind=block display=inline behavior=document-root children=[b1] marker=none replaced=none intrinsic=none\n",
                "  b1: parent=b0 cb=b0 establishes-cb=yes fc=b0 establishes-fc=block block-participation=block-level source-id=2 source=element(\"div\") role=document-element kind=block display=block behavior=document-element children=[b2] marker=none replaced=none intrinsic=none\n",
                "    b2: parent=b1 cb=b1 establishes-cb=no fc=b1 establishes-fc=none block-participation=inline-level source-id=3 source=element(\"span\") role=ordinary-element kind=inline display=inline behavior=inline children=[b3] marker=none replaced=none intrinsic=none\n",
                "      b3: parent=b2 cb=b1 establishes-cb=no fc=b1 establishes-fc=none block-participation=inline-level source-id=4 source=text(\"x\") role=text-run kind=block display=inline behavior=text-run children=[] marker=none replaced=none intrinsic=none\n",
            )
        );
    }

    #[test]
    fn box_source_can_represent_future_non_dom_backed_boxes() {
        let dom = doc(vec![element(2, "div", Vec::new(), Vec::new())]);
        let styled = css::build_style_tree(&dom, None);
        let div = &styled.children[0];
        let source = BoxSource::Anonymous {
            parent: div,
            kind: AnonymousBoxKind::Block,
        };

        assert_eq!(source.direct_node_id(), None);
        assert!(source.direct_styled_node().is_none());
        assert_eq!(source.anchor_node_id(), Id(2));
        assert_eq!(source.anchor_styled_node().node_id, Id(2));
    }
}
