use css::{BoxMetrics, ComputedStyle, StyledNode};
use html::internal::Id;

use crate::{
    BlockFormattingParticipation, BoxId, BoxKind, BoxSource, ContainingBlockId,
    FormattingContextId, FormattingContextKind, InlineFormattingContextId,
    InlineFormattingParticipation, ListMarker, Rectangle, ReplacedKind, UsedContentSize,
    replaced::intrinsic::IntrinsicSize,
};

/// A geometry projection of one generated box-tree node.
///
/// `source` preserves whether the box is directly DOM-backed or generated by a
/// layout rule. `node` remains a source anchor during the current bridge phase
/// so downstream paint/input code can keep using existing DOM-oriented helpers
/// while anonymous boxes become explicit layout participants.
pub struct LayoutBox<'style_tree, 'dom> {
    pub box_id: BoxId,
    pub kind: BoxKind,
    pub style: &'style_tree ComputedStyle,
    pub source: BoxSource<'style_tree, 'dom>,
    pub node: &'style_tree StyledNode<'dom>,
    pub rect: Rectangle,
    pub children: Vec<LayoutBox<'style_tree, 'dom>>,
    pub containing_block: Option<ContainingBlockId>,
    pub establishes_containing_block: bool,
    pub formatting_context: Option<FormattingContextId>,
    pub establishes_formatting_context: Option<FormattingContextKind>,
    pub block_formatting_participation: BlockFormattingParticipation,
    pub inline_formatting_context: Option<InlineFormattingContextId>,
    pub establishes_inline_formatting_context: bool,
    pub inline_formatting_participation: InlineFormattingParticipation,
    pub list_marker: Option<ListMarker>,
    pub replaced: Option<ReplacedKind>,
    pub replaced_intrinsic: Option<IntrinsicSize>,
    pub used_content_size: Option<UsedContentSize>,
}

impl<'style_tree, 'dom> LayoutBox<'style_tree, 'dom> {
    pub fn box_id(&self) -> BoxId {
        self.box_id
    }

    /// Returns the anchor DOM node ID for this layout box.
    ///
    /// For DOM-backed boxes this is the direct source node. For anonymous or
    /// other generated boxes this is the source anchor used for inherited style
    /// and bridge compatibility. Use `direct_node_id()` when code needs to know
    /// whether the box directly represents a DOM node.
    pub fn node_id(&self) -> Id {
        self.source.anchor_node_id()
    }

    pub fn direct_node_id(&self) -> Option<Id> {
        self.source.direct_node_id()
    }

    pub fn containing_block(&self) -> Option<ContainingBlockId> {
        self.containing_block
    }

    pub fn establishes_containing_block(&self) -> bool {
        self.establishes_containing_block
    }

    pub fn formatting_context(&self) -> Option<FormattingContextId> {
        self.formatting_context
    }

    pub fn establishes_formatting_context(&self) -> Option<FormattingContextKind> {
        self.establishes_formatting_context
    }

    pub fn block_formatting_participation(&self) -> BlockFormattingParticipation {
        self.block_formatting_participation
    }

    pub fn inline_formatting_context(&self) -> Option<InlineFormattingContextId> {
        self.inline_formatting_context
    }

    pub fn establishes_inline_formatting_context(&self) -> bool {
        self.establishes_inline_formatting_context
    }

    pub fn inline_formatting_participation(&self) -> InlineFormattingParticipation {
        self.inline_formatting_participation
    }

    pub fn is_anonymous(&self) -> bool {
        matches!(self.source, BoxSource::Anonymous { .. })
    }

    pub fn source_node(&self) -> Option<&'style_tree StyledNode<'dom>> {
        self.source.direct_styled_node()
    }

    pub fn box_metrics(&self) -> BoxMetrics {
        if self.is_anonymous() {
            BoxMetrics::zero()
        } else {
            self.style.box_metrics()
        }
    }

    pub fn content_x_and_width(&self) -> (f32, f32) {
        let bm = self.box_metrics();
        let content_x = self.rect.x + bm.padding_left;
        let content_width = (self.rect.width - bm.padding_left - bm.padding_right).max(0.0);
        (content_x, content_width)
    }

    pub fn content_y(&self) -> f32 {
        self.rect.y + self.box_metrics().padding_top
    }

    pub fn content_height(&self) -> f32 {
        let bm = self.box_metrics();
        (self.rect.height - bm.padding_top - bm.padding_bottom).max(0.0)
    }
}
