//! Display-driven box generation classification.

use crate::{BoxKind, ReplacedKind};
use css::{Display, StyledNode};
use html::Node;

/// High-level reason a box exists in the generated box tree.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BoxGenerationRole {
    DocumentRoot,
    DocumentElement,
    OrdinaryElement,
    TextRun,
    Anonymous(AnonymousBoxKind),
    Marker,
}

/// Anonymous-box categories generated by layout-owned box-generation rules.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AnonymousBoxKind {
    Block,
    Inline,
}

/// Decision produced by display-to-box generation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DisplayBoxGeneration {
    SuppressSubtree(BoxSuppressionReason),
    GeneratePrincipalBox(PrincipalBox),
}

/// Reason a styled node does not generate a layout box.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BoxSuppressionReason {
    CommentNode,
    DisplayNone,
}

/// Metadata for the principal box generated by one styled source.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PrincipalBox {
    role: BoxGenerationRole,
    kind: BoxKind,
    behavior: DisplayBoxBehavior,
}

impl PrincipalBox {
    pub fn role(self) -> BoxGenerationRole {
        self.role
    }

    pub fn kind(self) -> BoxKind {
        self.kind
    }

    pub fn behavior(self) -> DisplayBoxBehavior {
        self.behavior
    }
}

/// Supported display-driven layout participation behavior.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DisplayBoxBehavior {
    DocumentRoot,
    DocumentElement,
    Block,
    Inline,
    InlineBlock,
    ListItem,
    TextRun,
    ReplacedInline,
    Anonymous,
    Marker,
}

pub(super) fn display_box_generation(
    styled: &StyledNode<'_>,
    parent_role: Option<BoxGenerationRole>,
    replaced_kind: Option<ReplacedKind>,
) -> DisplayBoxGeneration {
    if matches!(styled.node, Node::Comment { .. }) {
        return DisplayBoxGeneration::SuppressSubtree(BoxSuppressionReason::CommentNode);
    }

    if matches!(styled.node, Node::Element { .. }) && styled.style.display() == Display::None {
        return DisplayBoxGeneration::SuppressSubtree(BoxSuppressionReason::DisplayNone);
    }

    let role = box_generation_role(styled, parent_role);
    DisplayBoxGeneration::GeneratePrincipalBox(principal_box_for_styled_node(
        styled,
        role,
        replaced_kind,
    ))
}

fn box_generation_role(
    styled: &StyledNode<'_>,
    parent_role: Option<BoxGenerationRole>,
) -> BoxGenerationRole {
    match styled.node {
        Node::Document { .. } => BoxGenerationRole::DocumentRoot,
        Node::Element { .. } => {
            if parent_role == Some(BoxGenerationRole::DocumentRoot) {
                BoxGenerationRole::DocumentElement
            } else {
                BoxGenerationRole::OrdinaryElement
            }
        }
        Node::Text { .. } => BoxGenerationRole::TextRun,
        Node::Comment { .. } => unreachable!("comments do not generate boxes"),
    }
}

fn principal_box_for_styled_node(
    styled: &StyledNode<'_>,
    role: BoxGenerationRole,
    replaced_kind: Option<ReplacedKind>,
) -> PrincipalBox {
    let style = &styled.style;
    let (kind, behavior) = match role {
        BoxGenerationRole::DocumentRoot => (BoxKind::Block, DisplayBoxBehavior::DocumentRoot),
        BoxGenerationRole::DocumentElement => (BoxKind::Block, DisplayBoxBehavior::DocumentElement),
        BoxGenerationRole::TextRun => (BoxKind::Block, DisplayBoxBehavior::TextRun),
        BoxGenerationRole::Anonymous(_) => (BoxKind::Block, DisplayBoxBehavior::Anonymous),
        BoxGenerationRole::Marker => (BoxKind::Block, DisplayBoxBehavior::Marker),
        BoxGenerationRole::OrdinaryElement => {
            if replaced_kind.is_some()
                && matches!(style.display(), Display::Inline | Display::InlineBlock)
            {
                (BoxKind::ReplacedInline, DisplayBoxBehavior::ReplacedInline)
            } else {
                match style.display() {
                    Display::Block => (BoxKind::Block, DisplayBoxBehavior::Block),
                    Display::Inline => (BoxKind::Inline, DisplayBoxBehavior::Inline),
                    Display::InlineBlock => (BoxKind::InlineBlock, DisplayBoxBehavior::InlineBlock),
                    Display::ListItem => (BoxKind::Block, DisplayBoxBehavior::ListItem),
                    Display::None => unreachable!("display:none is suppressed before box creation"),
                }
            }
        }
    };

    PrincipalBox {
        role,
        kind,
        behavior,
    }
}

pub(super) fn principal_participates_inline(principal: PrincipalBox) -> bool {
    matches!(
        principal.behavior(),
        DisplayBoxBehavior::Inline
            | DisplayBoxBehavior::InlineBlock
            | DisplayBoxBehavior::TextRun
            | DisplayBoxBehavior::ReplacedInline
    )
}
