//! Source identity for generated layout boxes.

use css::StyledNode;
use html::internal::Id;
use std::fmt;

use super::display::AnonymousBoxKind;

/// Source relationship for a generated layout box.
///
/// Boxes may be directly DOM-backed or generated by layout-owned box-generation
/// rules. Anonymous boxes are generated for the supported block/inline mixing
/// subset. Marker boxes are reserved for future independent marker generation.
#[derive(Clone, Copy)]
pub enum BoxSource<'style_tree, 'dom> {
    DomNode(&'style_tree StyledNode<'dom>),
    Anonymous {
        parent: &'style_tree StyledNode<'dom>,
        kind: AnonymousBoxKind,
    },
    Marker {
        list_item: &'style_tree StyledNode<'dom>,
    },
}

impl fmt::Debug for BoxSource<'_, '_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
            BoxSource::DomNode(node) => f
                .debug_struct("DomNode")
                .field("node_id", &node.node_id)
                .finish(),
            BoxSource::Anonymous { parent, kind } => f
                .debug_struct("Anonymous")
                .field("parent_node_id", &parent.node_id)
                .field("kind", &kind)
                .finish(),
            BoxSource::Marker { list_item } => f
                .debug_struct("Marker")
                .field("list_item_node_id", &list_item.node_id)
                .finish(),
        }
    }
}

impl<'style_tree, 'dom> BoxSource<'style_tree, 'dom> {
    pub fn direct_styled_node(self) -> Option<&'style_tree StyledNode<'dom>> {
        match self {
            BoxSource::DomNode(node) => Some(node),
            BoxSource::Anonymous { .. } | BoxSource::Marker { .. } => None,
        }
    }

    pub fn anchor_styled_node(self) -> &'style_tree StyledNode<'dom> {
        match self {
            BoxSource::DomNode(node) => node,
            BoxSource::Anonymous { parent, .. } => parent,
            BoxSource::Marker { list_item } => list_item,
        }
    }

    pub fn direct_node_id(self) -> Option<Id> {
        self.direct_styled_node().map(|node| node.node_id)
    }

    pub fn anchor_node_id(self) -> Id {
        self.anchor_styled_node().node_id
    }
}
